[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/nix/store/$(ls -la /nix/store | grep 'typescript' | grep '4096' | awk '{print $9}' | sed -n '$p')/node_modules/typescript/lib"}, environment = "node" } 

[language-server.eslint]
command = "vscode-eslint-language-server"
args = [ "--stdio" ]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls", "eslint"]
formatter = { command = "npx", args = [ "prettier", "--stdin", "--parser", "html" ] }
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls", "eslint" ]
formatter = { command = "npx", args = [ "prettier", "--stdin", "--parser", "css" ] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "eslint" ]
formatter = { command = "npx", args = [ "prettier", "--stdin", "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "eslint" ]
formatter = { command = "npx", args = [ "prettier", "--stdin", "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "eslint" ]
formatter = { command = "npx", args = [ "prettier", "--stdin", "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "tailwindcss-ls", "eslint" ]
formatter = { command = "npx", args = [ "prettier", "--stdin", "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls", "eslint" ]
auto-format = true
formatter = { command = "npx", args = [ "prettier", "--plugin", "prettier-plugin-svelte", "--stdin"] }

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls", "eslint" ]
formatter = { command = "npx", args = [ "prettier", "--plugin", "prettier-plugin-astro", "--parser", "astro", "--stdin"] }

[[language]]
name = "mdx"
language-servers = [ "marksman" ]
scope = "text.mdx"
file-types = [ "mdx" ]
